# Generated by Django 4.1.3 on 2022-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.TextField(blank=True, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.TextField(blank=True, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.TextField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='products',
            name='structure',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='products',
            name='thickness',
            field=models.TextField(blank=True, null=True, verbose_name='Толщина инструмента'),
        ),
        migrations.AddField(
            model_name='products',
            name='tr_length',
            field=models.TextField(blank=True, null=True, verbose_name='Длина нити'),
        ),
        migrations.AlterField(
            model_name='products',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
