# Generated by Django 4.1.3 on 2022-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croch', '0002_products_color_products_material_products_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(max_length=10, null=True, verbose_name='Цена'),
        ),
    ]
