# Generated by Django 4.1.3 on 2023-04-11 16:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croch', '0003_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='products',
            name='structure',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='products',
            name='thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Толщина инструмента'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tr_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина нити'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('avatar', models.ImageField(blank=True, default='woman.jpg', upload_to='avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Аватар')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'app_profiles',
                'ordering': ('user',),
            },
        ),
    ]
