# Generated by Django 4.1.3 on 2023-06-10 11:55

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croch', '0006_comment_comment_app_comment_time_cr_0c0ec5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('Банковская карта', 'Банковская карта')], default='Банковская карта', max_length=50, verbose_name='Метод оплаты')),
                ('delivery_method', models.CharField(choices=[('Почта России', 'Почта России'), ('СДЭК', 'СДЭК')], default='Самовывоз', max_length=50, verbose_name='Доставка')),
                ('status', models.CharField(choices=[('Получен', 'Получен'), ('В пути', 'В пути'), ('Заказ обрабатывается', 'Заказ обрабатывается')], default='Заказ подтвержден', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='Номер карты')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='Срок действия')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='CVV/CVC')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='croch.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='product/')),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croch.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('cover', models.ImageField(upload_to='product/')),
                ('prod_id', models.CharField(max_length=50, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croch.cart')),
            ],
        ),
    ]
